Belval/pdf2image

README.md

The previous Windows link didn't provide the necessary binaries `pdfinfo`, etc. but only two .dll files. This new link (http://blog.alivate.com.au/poppler-windows/) can save hours of trial and errors!

Updated link for Windows

---

.travis.yml
README.md
setup.py
tests.py

I have documented python 2.7 and 3.3+ support in the README and added a polyfill for the tests, where `tempfile.TemporaryDirectory` is not available in python 2.7. The source code was already compatible to python 2.7.

Adds python 2.7 support

---

pdf2image/pdf2image.py

Right now, there's no option to provide an output filename to the command.
This Pull Request adds an option to do so.
In case, there's no filename provided, it takes the filename of the input file. This will be useful in case there's a need to convert many files and to trace back to the pdf from which the image was extracted.

Add an option to provide output filename.

---

pdf2image/parsers.py

The I-E-N-D can be found in PNG buffers as a non-terminating sequence. This was not handled properly before.
The data that caused this bug to be uncovered is not free to distribute, therefore I made a private test that will not be part of the codebase.
Fixes: #52

Add support for buffer with IEND bytes

---

pdf2image/pdf2image.py

Fixes an issue where `libpoppler` had to be in the working directory for poppler-utils to work.

Update LD_LIBRARY_PATH with poppler_path if given

---

pdf2image/pdf2image.py
setup.py
tests.py

This is done to emulate Python slices where
```py
a = [0, 1, 2]
a[2:0]
```
Due to how `pdftoppm` and `pdftocairo` work, `first_page=1` with `last_page=1` will still return the first page. Even though in Python it would return an empty list.
Fixes #65

Handle first_page greater than last_page

---

README.md
pdf2image/pdf2image.py
tests.py

Add a `single_file=False` optional parameter for `convert_from_path` and `convert_from_bytes`. It uses the `-singlefile` argument for `pdftoppm` and `pdftocairo`.
```
-singlefile              : write only the first page and do not add digits
```
Fixes: #71

Add single_file parameter

---

pdf2image/pdf2image.py
tests.py

Instead of simply looking for the `output_file` string in the filename, use `.startswith()`. Also match the extension.
Fixes: #69

Prevent wrong filename matching

---

pdf2image/pdf2image.py

`poppler_path` is listed twice. This removes the one that is in the wrong position compared to the function definition.

Remove duplicate parameter description from docstring

---

pdf2image/generators.py
pdf2image/pdf2image.py
tests.py

Generators in Python are special objects that can be iterated over, and with each iteration they'll yield a new output depending on what they are.
By separating the logic of creating incremental filenames away from the parts that create files, and by allowing user to supply a custom generator of their own we allow the flexibility to explode.
Supplying anything else that isn't a generator is still accounted for legacy purposes.

Implement generator support for output filenames

---

pdf2image/pdf2image.py

As outlined in #87, passing Path objects as arguments breaks convert_from_path and raises a PDFInfoNotInstalledError exception, which is inconvenient, confusing and frustrating at the same time.
This PR adds logic for handling Pathlike objects as arguments, where appropriate.

Add recognition of pathlike objects as arguments

---

docs/reference.md
pdf2image/pdf2image.py
tests.py

I've had a few problems with memory/resources being used up rapidly when converting many PDFs, even when using a temporary folder (I reached the opened files limit then). Initially I thought the function returns a list of paths, and I was surprised to find that the images were preloaded, which I think may be unnecessary in some cases (it was in mine), so I added a quick option to only return the paths rather than load and return the images. I don't think it makes sense to use it in conjunction with the `in_memory` option so I've made them mutually exclusive (you cannot load images into memory if all you want is the paths).
Closes (a possible solution for) #80 and #31.
Thanks for this great little gem!

Add paths_only option

---

pdf2image/__init__.py
pdf2image/pdf2image.py
tests.py

Adds matching `pdfinfo_from_path` and `pdfinfo_from_bytes`. I would rather not use the same `_from_something` suffix, but I wanted to keep the interface consistent.
They both return a dictionary of all the parameters extracted by `pdfinfo`.
Fixes: #105

Add pdfinfo_from_bytes and pdfinfo_from_path

---

docs/reference.md
pdf2image/pdf2image.py
tests.py

Adds the `jpegopt`parameters to `convert_from_path()` and `convert_from_bytes()`.
Requires `fmt="jpeg"` and is provided as dict such as:
```python
jpegopt: {"quality": 100, "optimize": True, "progressive": False}
```
Full example:
```python
pdf2image.convert_from_path(<path_to_pdf>, size=3500, fmt="jpeg", jpegopt={"quality":100, "optimize":True})
```
Tests not added yet.

Add jpegopt

---

pdf2image/exceptions.py
pdf2image/generators.py
pdf2image/parsers.py
pdf2image/pdf2image.py
tests.py

Make default generators threadsafe 

---

pdf2image/generators.py
pdf2image/pdf2image.py

Not too sure how to explain the bug itself, but it worked fine on Linux through luck and magic as the default generator was not actually a generator anymore so it should have blown up.
I will merge this fix as soon as the CI pass and create version 1.12.1.
I will also write a post-mortem because it seems to indicate that there are differences between platforms that I was not aware of.
Fixes: #127

Urgent fix generator Windows

---

README.md

For windows users without admin rights, adding poppler to PATH is not a feasible option. However using the poppler_path argument is a simpler method for users to get started easily & should be shown in the README steps.

Highlight another way to use Poppler path on Win clearly

---

pdf2image/pdf2image.py
setup.py

Hi,
The purpose of the this PR is to add the ability to retrieve the PDF creation date as a raw string instead of the formatted string returned by default by `pdfinfo`.
I simply added the `-rawdates` option to `pdfinfo_from_bytes` and `pdfinfo_from_path`. I also added the missing `userpw` option to `pdfinfo_from_bytes`. The reason I wanted the date as a raw string is because of the timezone. This information is lost when the timestamp is formatted.
Hope that helps. Thank you for the repo!
Best,
Louis

Handle rawdates

---

pdf2image/exceptions.py
pdf2image/pdf2image.py

When I use pdf2image to process a large number of pdf files, always hold when exec poppler subprocess.
I think we can add a timeout arg to slove this problem.

Add timeout expired when run poppler command timeout.

---

README.md
pdf2image/pdf2image.py
tests.py

This is a complementary PR to #156 which adds tests and adds the parameter to the `from_bytes` versions of the functions.

Add test for timeout functionality

---

tests.py

This is to make sure that the tests fail when a parameter was added to convert_from_path and not convert_from_bytes and vice-versa.

Add test to ensure same parameter count

---

pdf2image/pdf2image.py

With the new timeout feature, the default timeout was set to 600 and 60 for convert and pdfinfo respectively.
Those value would break the default behavior and as such, I prefer to set them to None so the module user can decide what would be a good value for his/her usecase.

Set default timeout to None

---

.travis.yml
pdf2image/pdf2image.py

This fixes the version detection issue by having `_get_poppler_version` return both the major and minor numbers.

Fix version detection

---

README.md
docs/installation.md

Reference [Wrong page range given: the first page (1) can not be after the last page (0)](https://github.com/Belval/pdf2image/issues/234) issue. But now is documented with the error and the solution.
First I add into the know issues list and then in `installation.md` I explain the solution.

documentation about solution for docusign issue

---

pdf2image/pdf2image.py

Fixes: #249 
Unused imported was added in 1.16.1. Also need to pull the release and remove the version from PyPI.
Will need to investigate why the CI didn't raise and issue.

Remove posix import

---

setup.py

Adds a py.typed file in order to be [pep-0561](https://peps.python.org/pep-0561/#packaging-type-information) compliant. Closes issue #255.

Closes #255; added py.typed file.

---

.gitignore
pdf2image/parsers.py
pdf2image/pdf2image.py
tests.py

WebP is a modern, open source image format created by Google which boasts a lot of [advantages](https://developers.google.com/speed/webp) over jpeg and png. This PR adds support to write webp files from within pdf2image library by using Pillow's built in support for webp image format. This PR also rectifies some of the test names which weren't correct.

Add support for WebP image format

---

pdf2image/__init__.py

Update __init__.py to match [https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface](https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface) to mark exports as public

Update __init__.py to mark exports as public

---

pdf2image/pdf2image.py

add -f and -l to pdfinfo

---

tests.py

This removes the test dependency on
https://pypi.org/project/memory-profiler/ when the `PROFILE_MEMORY` environment variable is not set.

Import memory_profiler only when it is enabled

---

pdf2image/pdf2image.py

Fixed the issue: when the `single_file` is `True` and the `thread_count` is greater than 1, the `thread_output_file = next(output_file)` will fail.

Fixed the issue: when the `single_file` is `True` and the `thread_count` is greater than 1, the `thread_output_file = next(output_file)` will fail.
